-- Optional: server/_shared.lua creates these automatically on start.
-- (table names can be changed in Config.Tables)

CREATE TABLE IF NOT EXISTS `ems_reports` (
  `id` INT NOT NULL AUTO_INCREMENT, `citizenid` VARCHAR(50) NOT NULL, `author_name` VARCHAR(100) NOT NULL,
  `report_type` VARCHAR(50) NOT NULL DEFAULT 'Treatment', `title` VARCHAR(150) NOT NULL,
  `patient_name` VARCHAR(100) DEFAULT NULL, `patient_cid` VARCHAR(50) DEFAULT NULL,
  `involved` VARCHAR(255) DEFAULT NULL, `details` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `patient_cid` (`patient_cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ems_directives` (
  `id` INT NOT NULL AUTO_INCREMENT, `title` VARCHAR(150) NOT NULL, `body` TEXT NOT NULL,
  `priority` VARCHAR(20) NOT NULL DEFAULT 'normal', `posted_by` VARCHAR(100) NOT NULL,
  `posted_by_cid` VARCHAR(50) NOT NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ems_mdt_logs` (
  `id` INT NOT NULL AUTO_INCREMENT, `citizenid` VARCHAR(50) NOT NULL, `medic_name` VARCHAR(100) NOT NULL,
  `action` VARCHAR(100) NOT NULL, `details` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ems_ward_board` (
  `id` INT NOT NULL AUTO_INCREMENT, `citizenid` VARCHAR(50) NOT NULL, `author_name` VARCHAR(100) NOT NULL,
  `patient_name` VARCHAR(150) NOT NULL, `patient_cid` VARCHAR(50) DEFAULT NULL, `bed` VARCHAR(30) DEFAULT NULL,
  `diagnosis` VARCHAR(500) NOT NULL, `severity` VARCHAR(20) NOT NULL DEFAULT 'stable',
  `active` TINYINT(1) NOT NULL DEFAULT 1, `discharged_by` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ems_suspended` (
  `citizenid` VARCHAR(50) NOT NULL, `suspended_by` VARCHAR(100) NOT NULL, `reason` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ems_patients` (
  `citizenid` VARCHAR(50) NOT NULL, `allergies` VARCHAR(500) DEFAULT NULL, `conditions` VARCHAR(500) DEFAULT NULL,
  `medications` VARCHAR(500) DEFAULT NULL, `notes` TEXT DEFAULT NULL, `updated_by` VARCHAR(100) DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ems_bills` (
  `id` INT NOT NULL AUTO_INCREMENT, `citizenid` VARCHAR(50) NOT NULL, `medic_name` VARCHAR(100) NOT NULL,
  `patient_name` VARCHAR(100) NOT NULL, `patient_cid` VARCHAR(50) DEFAULT NULL, `treatment` VARCHAR(255) NOT NULL,
  `amount` INT NOT NULL DEFAULT 0, `paid` TINYINT(1) NOT NULL DEFAULT 0, `notes` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ems_funds` (
  `job_name` VARCHAR(50) NOT NULL, `amount` INT NOT NULL DEFAULT 0, PRIMARY KEY (`job_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ems_applications` (
  `id` INT NOT NULL AUTO_INCREMENT, `citizenid` VARCHAR(50) NOT NULL, `applicant_name` VARCHAR(100) NOT NULL,
  `applicant_age` INT NOT NULL DEFAULT 18, `experience` VARCHAR(500) NOT NULL, `contact` VARCHAR(50) DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'Pending', `reviewed_by` VARCHAR(50) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
