-- Optional: server/_shared.lua and server/wanted.lua auto-create these on start.
CREATE TABLE IF NOT EXISTS `police_reports` (
  `id` INT NOT NULL AUTO_INCREMENT, `citizenid` VARCHAR(50) NOT NULL, `author_name` VARCHAR(100) NOT NULL,
  `report_type` VARCHAR(50) NOT NULL DEFAULT 'General', `title` VARCHAR(150) NOT NULL,
  `involved` VARCHAR(255) DEFAULT NULL, `details` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `police_directives` (
  `id` INT NOT NULL AUTO_INCREMENT, `title` VARCHAR(150) NOT NULL, `body` TEXT NOT NULL,
  `priority` VARCHAR(20) NOT NULL DEFAULT 'normal', `posted_by` VARCHAR(100) NOT NULL,
  `posted_by_cid` VARCHAR(50) NOT NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `police_mdt_logs` (
  `id` INT NOT NULL AUTO_INCREMENT, `citizenid` VARCHAR(50) NOT NULL, `officer_name` VARCHAR(100) NOT NULL,
  `action` VARCHAR(100) NOT NULL, `details` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `police_bolos` (
  `id` INT NOT NULL AUTO_INCREMENT, `citizenid` VARCHAR(50) NOT NULL, `author_name` VARCHAR(100) NOT NULL,
  `subject_name` VARCHAR(150) DEFAULT NULL, `subject_desc` VARCHAR(255) DEFAULT NULL,
  `vehicle_plate` VARCHAR(20) DEFAULT NULL, `reason` TEXT NOT NULL, `priority` VARCHAR(20) NOT NULL DEFAULT 'normal',
  `active` TINYINT(1) NOT NULL DEFAULT 1, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `police_suspended` (
  `citizenid` VARCHAR(50) NOT NULL, `suspended_by` VARCHAR(100) NOT NULL, `reason` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `police_wanted` (
  `id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL, `charges` VARCHAR(500) NOT NULL,
  `danger_level` VARCHAR(20) NOT NULL DEFAULT 'Medium', `last_seen` VARCHAR(150) DEFAULT NULL,
  `reward` INT NOT NULL DEFAULT 0, `posted_by` VARCHAR(100) NOT NULL, `posted_by_cid` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `police_funds` (
  `job_name` VARCHAR(50) NOT NULL, `amount` INT NOT NULL DEFAULT 0, PRIMARY KEY (`job_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
