Config = {}

Config.Items = {}
Config.RefreshTime = 30 -- mnt

Config.GlobalItems = {
    [1] = {
        name = "lockpick",
        price = 50,
        amount = 300,
        dAmount = 300,
        minPrice = 50,
        maxPrice = 150,
        info = {},
        type = "item",
        slot = 1,
    },
     [2] = {
         name = "repairkit",
         price = 50,
         amount = 300,
         dAmount = 300,
         minPrice = 50,
         maxPrice = 200,
         info = {},
         type = "item",
         slot = 1,
     },
    [3] = {
        name = "cleaningkit",
        price = 100,
        amount = 300,
        dAmount = 300,
        minPrice = 50,
        maxPrice = 150,
        info = {},
        type = "item",
        slot = 1,
    },      
    [4] = {
        name = "diving_gear",
        price = 500,
        amount = 300,
        dAmount = 300,
        minPrice = 500,
        maxPrice = 700,
        info = {},
        type = "item",
        slot = 1,
    },                        
    [5] = {
        name = "syphoningkit",
        price = 3000,
        amount = 1,
        dAmount = 1,
        minPrice = 1000,
        maxPrice = 1300,
        info = {
            gasamount = 0
        },
        type = "item",
        slot = 1,
    },   
    [6] = {
        name = "blowtorch",
        price = 500,
        amount = 300,
        dAmount = 300,
        minPrice = 480,
        maxPrice = 600,
        info = {},
        type = "item",
        slot = 1,
    },   
    [7] = {
        name = "screwdriverset",
        price = 200,
        amount = 300,
        dAmount = 300,
        minPrice = 150,
        maxPrice = 280,
        info = {},
        type = "item",
        slot = 1,
    },  
    [8] = {
        name = "tire",
        price = 900,
        amount = 5,
        dAmount = 300,
        minPrice = 150,
        maxPrice = 280,
        info = {},
        type = "item",
        slot = 1,
    },
    -- [9] = {
    --     name = "bag",
    --     price = 700,
    --     amount = 5,
    --     dAmount = 300,
    --     minPrice = 150,
    --     maxPrice = 280,
    --     info = {},
    --     type = "item",
    --     slot = 1,
    -- },              
    [9] = {
        name = "a4sheets",
        price = 100,
        amount = 1,
        dAmount = 300,
        minPrice = 150,
        maxPrice = 280,
        info = {},
        type = "item",
        slot = 1,
    },               
}
