// Builds the radial menu icon sprite from tools/icons.html with Font Awesome's
// own JS (tools/fontawesome-all.min.js) and writes it into html/ui.html between
// <!-- ICONS:START --> and <!-- ICONS:END -->. The game never loads Font
// Awesome itself (it was 13 MB of JS + CSS for ~180 icons).
//   cd qb-radialmenu && npm i jsdom && node tools/build-icons.js
const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');

const root = path.join(__dirname, '..');
const listHtml = fs.readFileSync(path.join(__dirname, 'icons.html'), 'utf8');
const tags = listHtml.match(/<i\s+data-fa-symbol="[^"]+"[^>]*><\/i>/g) || [];
const dom = new JSDOM('<!doctype html><html><head></head><body>' + tags.join('\n') + '</body></html>', { runScripts: 'outside-only' });
const w = dom.window;
w.FontAwesomeConfig = { autoReplaceSvg: true, observeMutations: false, searchPseudoElements: false };
w.eval(fs.readFileSync(path.join(__dirname, 'fontawesome-all.min.js'), 'utf8'));

const keepNode = ['d', 'class', 'opacity', 'fill', 'transform', 'cx', 'cy', 'r', 'x', 'y', 'width', 'height', 'points'];
w.FontAwesome.dom.i2svg({ node: w.document.body }).then(() => {
    const seen = new Set();
    let sprite = '';
    w.document.querySelectorAll('symbol').forEach((s) => {
        if (seen.has(s.id)) return;
        seen.add(s.id);
        const c = s.cloneNode(true);
        for (const a of Array.from(c.attributes)) if (a.name !== 'id' && a.name !== 'viewBox') c.removeAttribute(a.name);
        c.querySelectorAll('*').forEach((n) => {
            for (const a of Array.from(n.attributes)) if (!keepNode.includes(a.name)) n.removeAttribute(a.name);
            if (n.getAttribute('class') === 'fa-secondary') n.setAttribute('opacity', '0.4'); // duotone second layer
        });
        sprite += c.outerHTML.replace(/\s+xmlns="[^"]*"/g, '') + '\n';
    });
    const wanted = [...new Set(tags.map((t) => t.match(/data-fa-symbol="([^"]+)"/)[1]))];
    const missing = wanted.filter((id) => !seen.has(id));
    if (missing.length) console.warn('Not found in Font Awesome (check the class):', missing.join(', '));

    const uiPath = path.join(root, 'html', 'ui.html');
    const ui = fs.readFileSync(uiPath, 'utf8');
    const block = '<!-- ICONS:START (generated by tools/build-icons.js — edit tools/icons.html instead) -->\n' +
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n' + sprite + '</svg>\n<!-- ICONS:END -->';
    const out = ui.replace(/<!-- ICONS:START[\s\S]*?<!-- ICONS:END -->/, () => block);
    if (out === ui && !ui.includes('ICONS:START')) throw new Error('markers not found in html/ui.html');
    fs.writeFileSync(uiPath, out);
    console.log(`icons: ${seen.size}/${wanted.length}, sprite ${(sprite.length / 1024).toFixed(1)} KB`);
}).catch((e) => { console.error(e); process.exit(1); });
